### ISSUE TITLE
support for full URL instead of just paths

### ISSUE THREAD

**Issue by robotarmy** [trek/pretender#63]
Hi,
I am trying to POST to a complete url that is registered in pretender.

POST http://yyy-api.xxx.local:6200/something/v1/cake

I can register a simple get request "/fish" but when I try to register 'http://moo.local/fish" 

I don't get a match.

What would it take to support full URLs?

**Comment by balinterdi** [comment]
One way around that is to set up a proxy instead of sending requests directly to the host (via CORS).

You can do that with `ember generate http-proxy yyy-api http://yyy-api.xxx.local:6200`. You can then just post to `/yyy-api` and stub out that URL in Pretender.

That said, I'd find that support for full URLs really helpful. In one of the applications I'm working on, the app needs to send requests to a domain that is not known beforehand (to check if a subdomain provided by the user is available: *.example.com where * is provided by the user when they create their account), and I can't use the above proxy solution for that case.

**Comment by trek** [comment]
Closing in favor of #66
